set(SOURCE_FILES
	"${SOURCE_DIR}/Data.cpp"
	"${SOURCE_DIR}/Grammar.cpp"
	"${SOURCE_DIR}/Input.cpp"
	"${SOURCE_DIR}/Logging.cpp" 
	"${SOURCE_DIR}/Session.cpp"
	"${SOURCE_DIR}/Settings.cpp"
	"${SOURCE_DIR}/TaskController.cpp"
	"${SOURCE_DIR}/ThreadSafe.cpp"
	"${SOURCE_DIR}/Utility.cpp"
)
